# Exploratory Data Analysis

Pull data from f1db and create feature vectors.

from

In [10]:
import sys
from pathlib import Path

# Get the project root (up one level from 'notebooks')
project_root = Path.cwd().parent

# Add the project root to sys.path if it's not already there
if str(project_root) not in sys.path:
    sys.path.append(str(project_root))

# Now you can import from the src directory
from src.database import F1DataManager

# Initialize the manager
db = F1DataManager()
#query = "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name"
query = """
SELECT name, type
FROM sqlite_master
WHERE type IN ('table', 'view')
  AND name NOT LIKE 'sqlite_%'
ORDER BY type, name
"""
tables = db.query(query)
print(tables)

                                name   type
0                            chassis  table
1                            circuit  table
2                        constructor  table
3             constructor_chronology  table
4                          continent  table
5                            country  table
6                             driver  table
7         driver_family_relationship  table
8                             engine  table
9                engine_manufacturer  table
10                           entrant  table
11                        grand_prix  table
12                              race  table
13         race_constructor_standing  table
14                         race_data  table
15              race_driver_standing  table
16                            season  table
17                season_constructor  table
18       season_constructor_standing  table
19                     season_driver  table
20            season_driver_standing  table
21        season_engine_manufacturer  table
22                    season_entrant  table
23            season_entrant_chassis  table
24        season_entrant_constructor  table
25             season_entrant_driver  table
26             season_entrant_engine  table
27  season_entrant_tyre_manufacturer  table
28          season_tyre_manufacturer  table
29                 tyre_manufacturer  table
30          driver_of_the_day_result   view
31                       fastest_lap   view
32            free_practice_1_result   view
33            free_practice_2_result   view
34            free_practice_3_result   view
35            free_practice_4_result   view
36                          pit_stop   view
37             pre_qualifying_result   view
38               qualifying_1_result   view
39               qualifying_2_result   view
40                 qualifying_result   view
41                       race_result   view
42          sprint_qualifying_result   view
43                sprint_race_result   view
44     sprint_starting_grid_position   view
45            starting_grid_position   view
46                 warming_up_result   view

In [16]:
# Try to find info for a particular race, Round 1 2025 (Bahrain)
query = "SELECT id, official_name FROM race WHERE year = 2025 AND official_name LIKE '%Bahrain%'"
race_info = db.query(query)
print(race_info)

     id                               official_name
0  1129  Formula 1 Gulf Air Bahrain Grand Prix 2025

In [46]:
# view available fields within race result
query = "PRAGMA table_info(race_data);"
out = db.query(query)
with open("race_data_names.txt", 'w') as f:
    for _, row in out.iterrows():
        f.write(f"{row['name']}\n")

In [ ]:
query = f"SELECT * FROM race_data WHERE race_id = {race_info.iloc[0]['id']}"
print(query)
db.query(query)

SELECT * FROM race_data WHERE race_id = 1126

,race_id,type,position_display_order,position_number,position_text,driver_number,driver_id,constructor_id,engine_manufacturer_id,tyre_manufacturer_id,...,fastest_lap_time_millis,fastest_lap_gap,fastest_lap_gap_millis,fastest_lap_interval,fastest_lap_interval_millis,pit_stop_stop,pit_stop_lap,pit_stop_time,pit_stop_time_millis,driver_of_the_day_percentage
0,1126,FREE_PRACTICE_1_RESULT,1,1.0,1,4,lando-norris,mclaren,mercedes,pirelli,...,NaN,None,NaN,None,NaN,NaN,NaN,None,NaN,NaN
1,1126,FREE_PRACTICE_1_RESULT,2,2.0,2,55,carlos-sainz-jr,williams,mercedes,pirelli,...,NaN,None,NaN,None,NaN,NaN,NaN,None,NaN,NaN
2,1126,FREE_PRACTICE_1_RESULT,3,3.0,3,16,charles-leclerc,ferrari,ferrari,pirelli,...,NaN,None,NaN,None,NaN,NaN,NaN,None,NaN,NaN
3,1126,FREE_PRACTICE_1_RESULT,4,4.0,4,81,oscar-piastri,mclaren,mercedes,pirelli,...,NaN,None,NaN,None,NaN,NaN,NaN,None,NaN,NaN
4,1126,FREE_PRACTICE_1_RESULT,5,5.0,5,1,max-verstappen,red-bull,honda-rbpt,pirelli,...,NaN,None,NaN,None,NaN,NaN,NaN,None,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
218,1126,DRIVER_OF_THE_DAY_RESULT,1,1.0,1,4,lando-norris,mclaren,mercedes,pirelli,...,NaN,None,NaN,None,NaN,NaN,NaN,None,NaN,20.7
219,1126,DRIVER_OF_THE_DAY_RESULT,2,2.0,2,81,oscar-piastri,mclaren,mercedes,pirelli,...,NaN,None,NaN,None,NaN,NaN,NaN,None,NaN,17.2
220,1126,DRIVER_OF_THE_DAY_RESULT,3,3.0,3,23,alexander-albon,williams,mercedes,pirelli,...,NaN,None,NaN,None,NaN,NaN,NaN,None,NaN,15.9
221,1126,DRIVER_OF_THE_DAY_RESULT,4,4.0,4,22,yuki-tsunoda,racing-bulls,honda-rbpt,pirelli,...,NaN,None,NaN,None,NaN,NaN,NaN,None,NaN,11.3
222,1126,DRIVER_OF_THE_DAY_RESULT,5,5.0,5,44,lewis-hamilton,ferrari,ferrari,pirelli,...,NaN,None,NaN,None,NaN,NaN,NaN,None,NaN,8.3

In [58]:
query = f"SELECT * FROM race_data WHERE race_id = {race_info.iloc[0]['id']} AND driver_id = 'lando-norris'"
print(query)
db.query(query)

SELECT * FROM race_data WHERE race_id = 1126 AND driver_id = 'lando-norris'

,race_id,type,position_display_order,position_number,position_text,driver_number,driver_id,constructor_id,engine_manufacturer_id,tyre_manufacturer_id,...,fastest_lap_time_millis,fastest_lap_gap,fastest_lap_gap_millis,fastest_lap_interval,fastest_lap_interval_millis,pit_stop_stop,pit_stop_lap,pit_stop_time,pit_stop_time_millis,driver_of_the_day_percentage
0,1126,FREE_PRACTICE_1_RESULT,1,1,1,4,lando-norris,mclaren,mercedes,pirelli,...,NaN,None,None,None,None,NaN,NaN,None,NaN,NaN
1,1126,FREE_PRACTICE_2_RESULT,3,3,3,4,lando-norris,mclaren,mercedes,pirelli,...,NaN,None,None,None,None,NaN,NaN,None,NaN,NaN
2,1126,FREE_PRACTICE_3_RESULT,10,10,10,4,lando-norris,mclaren,mercedes,pirelli,...,NaN,None,None,None,None,NaN,NaN,None,NaN,NaN
3,1126,QUALIFYING_RESULT,1,1,1,4,lando-norris,mclaren,mercedes,pirelli,...,NaN,None,None,None,None,NaN,NaN,None,NaN,NaN
4,1126,STARTING_GRID_POSITION,1,1,1,4,lando-norris,mclaren,mercedes,pirelli,...,NaN,None,None,None,None,NaN,NaN,None,NaN,NaN
5,1126,RACE_RESULT,1,1,1,4,lando-norris,mclaren,mercedes,pirelli,...,NaN,None,None,None,None,NaN,NaN,None,NaN,NaN
6,1126,FASTEST_LAP,1,1,1,4,lando-norris,mclaren,mercedes,pirelli,...,82167.0,None,None,None,None,NaN,NaN,None,NaN,NaN
7,1126,PIT_STOP,1,1,1,4,lando-norris,mclaren,mercedes,pirelli,...,NaN,None,None,None,None,1.0,2.0,13.341,13341.0,NaN
8,1126,PIT_STOP,18,18,18,4,lando-norris,mclaren,mercedes,pirelli,...,NaN,None,None,None,None,2.0,3.0,12.910,12910.0,NaN
9,1126,PIT_STOP,35,35,35,4,lando-norris,mclaren,mercedes,pirelli,...,NaN,None,None,None,None,3.0,4.0,12.804,12804.0,NaN
10,1126,PIT_STOP,60,60,60,4,lando-norris,mclaren,mercedes,pirelli,...,NaN,None,None,None,None,4.0,34.0,18.464,18464.0,NaN
11,1126,PIT_STOP,68,68,68,4,lando-norris,mclaren,mercedes,pirelli,...,NaN,None,None,None,None,5.0,44.0,18.031,18031.0,NaN
12,1126,DRIVER_OF_THE_DAY_RESULT,1,1,1,4,lando-norris,mclaren,mercedes,pirelli,...,NaN,None,None,None,None,NaN,NaN,None,NaN,20.7

In [67]:
query = f"SELECT * FROM race_data WHERE race_id = {race_info.iloc[0]['id']} AND type = 'FASTEST_LAP'"
print(query)
db.query(query)

SELECT * FROM race_data WHERE race_id = 1126 AND type = 'FASTEST_LAP'

,race_id,type,position_display_order,position_number,position_text,driver_number,driver_id,constructor_id,engine_manufacturer_id,tyre_manufacturer_id,...,fastest_lap_time_millis,fastest_lap_gap,fastest_lap_gap_millis,fastest_lap_interval,fastest_lap_interval_millis,pit_stop_stop,pit_stop_lap,pit_stop_time,pit_stop_time_millis,driver_of_the_day_percentage
0,1126,FASTEST_LAP,1,1,1,4,lando-norris,mclaren,mercedes,pirelli,...,82167,None,NaN,None,NaN,None,None,None,None,None
1,1126,FASTEST_LAP,2,2,2,30,liam-lawson,red-bull,honda-rbpt,pirelli,...,82970,+0.803,803.0,+0.803,803.0,None,None,None,None,None
2,1126,FASTEST_LAP,3,3,3,1,max-verstappen,red-bull,honda-rbpt,pirelli,...,83081,+0.914,914.0,+0.111,111.0,None,None,None,None,None
3,1126,FASTEST_LAP,4,4,4,81,oscar-piastri,mclaren,mercedes,pirelli,...,83242,+1.075,1075.0,+0.161,161.0,None,None,None,None,None
4,1126,FASTEST_LAP,5,5,5,5,gabriel-bortoleto,kick-sauber,ferrari,pirelli,...,84192,+2.025,2025.0,+0.950,950.0,None,None,None,None,None
5,1126,FASTEST_LAP,6,6,6,22,yuki-tsunoda,racing-bulls,honda-rbpt,pirelli,...,84194,+2.027,2027.0,+0.002,2.0,None,None,None,None,None
6,1126,FASTEST_LAP,7,7,7,44,lewis-hamilton,ferrari,ferrari,pirelli,...,84218,+2.051,2051.0,+0.024,24.0,None,None,None,None,None
7,1126,FASTEST_LAP,8,8,8,23,alexander-albon,williams,mercedes,pirelli,...,84597,+2.430,2430.0,+0.379,379.0,None,None,None,None,None
8,1126,FASTEST_LAP,9,9,9,12,kimi-antonelli,mercedes,mercedes,pirelli,...,84901,+2.734,2734.0,+0.304,304.0,None,None,None,None,None
9,1126,FASTEST_LAP,10,10,10,10,pierre-gasly,alpine,renault,pirelli,...,85020,+2.853,2853.0,+0.119,119.0,None,None,None,None,None
10,1126,FASTEST_LAP,11,11,11,63,george-russell,mercedes,mercedes,pirelli,...,85065,+2.898,2898.0,+0.045,45.0,None,None,None,None,None
11,1126,FASTEST_LAP,12,12,12,27,nico-hulkenberg,kick-sauber,ferrari,pirelli,...,85243,+3.076,3076.0,+0.178,178.0,None,None,None,None,None
12,1126,FASTEST_LAP,13,13,13,16,charles-leclerc,ferrari,ferrari,pirelli,...,85271,+3.104,3104.0,+0.028,28.0,None,None,None,None,None
13,1126,FASTEST_LAP,14,14,14,18,lance-stroll,aston-martin,mercedes,pirelli,...,85538,+3.371,3371.0,+0.267,267.0,None,None,None,None,None
14,1126,FASTEST_LAP,15,15,15,31,esteban-ocon,haas,ferrari,pirelli,...,86764,+4.597,4597.0,+1.226,1226.0,None,None,None,None,None
15,1126,FASTEST_LAP,16,16,16,87,oliver-bearman,haas,ferrari,pirelli,...,87603,+5.436,5436.0,+0.839,839.0,None,None,None,None,None
16,1126,FASTEST_LAP,17,17,17,14,fernando-alonso,aston-martin,mercedes,pirelli,...,88819,+6.652,6652.0,+1.216,1216.0,None,None,None,None,None

In [73]:
query = f"SELECT * FROM race_data WHERE race_id = {race_info.iloc[0]['id']} AND type = 'PIT_STOP' AND driver_id = 'lewis-hamilton'"
print(query)
db.query(query)

SELECT * FROM race_data WHERE race_id = 1126 AND type = 'PIT_STOP' AND driver_id = 'lewis-hamilton'

,race_id,type,position_display_order,position_number,position_text,driver_number,driver_id,constructor_id,engine_manufacturer_id,tyre_manufacturer_id,...,fastest_lap_time_millis,fastest_lap_gap,fastest_lap_gap_millis,fastest_lap_interval,fastest_lap_interval_millis,pit_stop_stop,pit_stop_lap,pit_stop_time,pit_stop_time_millis,driver_of_the_day_percentage
0,1126,PIT_STOP,8,8,8,44,lewis-hamilton,ferrari,ferrari,pirelli,...,None,None,None,None,None,1,2,15.002,15002,None
1,1126,PIT_STOP,25,25,25,44,lewis-hamilton,ferrari,ferrari,pirelli,...,None,None,None,None,None,2,3,16.191,16191,None
2,1126,PIT_STOP,42,42,42,44,lewis-hamilton,ferrari,ferrari,pirelli,...,None,None,None,None,None,3,4,14.789,14789,None
3,1126,PIT_STOP,54,54,54,44,lewis-hamilton,ferrari,ferrari,pirelli,...,None,None,None,None,None,4,33,18.526,18526,None
4,1126,PIT_STOP,80,80,80,44,lewis-hamilton,ferrari,ferrari,pirelli,...,None,None,None,None,None,5,47,20.802,20802,None

In [ ]:
query = f"SELECT * FROM race_data WHERE race_id = {race_info.iloc[0]['id']} AND driver_id = 'lando-norris'"
print(query)
db.query(query)

SELECT * FROM race_data WHERE race_id = 1126 AND driver_id = 'lando-norris'

,race_id,type,position_display_order,position_number,position_text,driver_number,driver_id,constructor_id,engine_manufacturer_id,tyre_manufacturer_id,...,fastest_lap_time_millis,fastest_lap_gap,fastest_lap_gap_millis,fastest_lap_interval,fastest_lap_interval_millis,pit_stop_stop,pit_stop_lap,pit_stop_time,pit_stop_time_millis,driver_of_the_day_percentage
0,1126,FREE_PRACTICE_1_RESULT,1,1,1,4,lando-norris,mclaren,mercedes,pirelli,...,NaN,None,None,None,None,NaN,NaN,None,NaN,NaN
1,1126,FREE_PRACTICE_2_RESULT,3,3,3,4,lando-norris,mclaren,mercedes,pirelli,...,NaN,None,None,None,None,NaN,NaN,None,NaN,NaN
2,1126,FREE_PRACTICE_3_RESULT,10,10,10,4,lando-norris,mclaren,mercedes,pirelli,...,NaN,None,None,None,None,NaN,NaN,None,NaN,NaN
3,1126,QUALIFYING_RESULT,1,1,1,4,lando-norris,mclaren,mercedes,pirelli,...,NaN,None,None,None,None,NaN,NaN,None,NaN,NaN
4,1126,STARTING_GRID_POSITION,1,1,1,4,lando-norris,mclaren,mercedes,pirelli,...,NaN,None,None,None,None,NaN,NaN,None,NaN,NaN
5,1126,RACE_RESULT,1,1,1,4,lando-norris,mclaren,mercedes,pirelli,...,NaN,None,None,None,None,NaN,NaN,None,NaN,NaN
6,1126,FASTEST_LAP,1,1,1,4,lando-norris,mclaren,mercedes,pirelli,...,82167.0,None,None,None,None,NaN,NaN,None,NaN,NaN
7,1126,PIT_STOP,1,1,1,4,lando-norris,mclaren,mercedes,pirelli,...,NaN,None,None,None,None,1.0,2.0,13.341,13341.0,NaN
8,1126,PIT_STOP,18,18,18,4,lando-norris,mclaren,mercedes,pirelli,...,NaN,None,None,None,None,2.0,3.0,12.910,12910.0,NaN
9,1126,PIT_STOP,35,35,35,4,lando-norris,mclaren,mercedes,pirelli,...,NaN,None,None,None,None,3.0,4.0,12.804,12804.0,NaN
10,1126,PIT_STOP,60,60,60,4,lando-norris,mclaren,mercedes,pirelli,...,NaN,None,None,None,None,4.0,34.0,18.464,18464.0,NaN
11,1126,PIT_STOP,68,68,68,4,lando-norris,mclaren,mercedes,pirelli,...,NaN,None,None,None,None,5.0,44.0,18.031,18031.0,NaN
12,1126,DRIVER_OF_THE_DAY_RESULT,1,1,1,4,lando-norris,mclaren,mercedes,pirelli,...,NaN,None,None,None,None,NaN,NaN,None,NaN,20.7

In [55]:
query = f"SELECT type FROM race_data WHERE race_id = {race_info.iloc[0]['id']}"
out = db.query(query)
oset = set()
for _, o in out.iterrows():
    oset.add(o['type'])
print(oset)

{'FREE_PRACTICE_2_RESULT', 'PIT_STOP', 'FASTEST_LAP', 'FREE_PRACTICE_1_RESULT', 'RACE_RESULT', 'FREE_PRACTICE_3_RESULT', 'STARTING_GRID_POSITION', 'QUALIFYING_RESULT', 'DRIVER_OF_THE_DAY_RESULT'}

In [23]:
# view available fields within race result
query = "PRAGMA table_info(race_result);"
db.query(query)

    cid                           name          type  notnull dflt_value  pk
0     0                        race_id       INTEGER        0       None   0
1     1         position_display_order       INTEGER        0       None   0
2     2                position_number       INTEGER        0       None   0
3     3                  position_text    VARCHAR(4)        0       None   0
4     4                  driver_number    VARCHAR(3)        0       None   0
5     5                      driver_id  VARCHAR(100)        0       None   0
6     6                 constructor_id  VARCHAR(100)        0       None   0
7     7         engine_manufacturer_id  VARCHAR(100)        0       None   0
8     8           tyre_manufacturer_id  VARCHAR(100)        0       None   0
9     9                     shared_car       BOOLEAN        0       None   0
10   10                           laps       INTEGER        0       None   0
11   11                           time   VARCHAR(20)        0       None   0
12   12                    time_millis       INTEGER        0       None   0
13   13                   time_penalty   VARCHAR(20)        0       None   0
14   14            time_penalty_millis       INTEGER        0       None   0
15   15                            gap   VARCHAR(20)        0       None   0
16   16                     gap_millis       INTEGER        0       None   0
17   17                       gap_laps       INTEGER        0       None   0
18   18                       interval   VARCHAR(20)        0       None   0
19   19                interval_millis       INTEGER        0       None   0
20   20                 reason_retired  VARCHAR(100)        0       None   0
21   21                         points  DECIMAL(8,2)        0       None   0
22   22                  pole_position       BOOLEAN        0       None   0
23   23  qualification_position_number       INTEGER        0       None   0
24   24    qualification_position_text    VARCHAR(4)        0       None   0
25   25           grid_position_number       INTEGER        0       None   0
26   26             grid_position_text    VARCHAR(2)        0       None   0
27   27               positions_gained       INTEGER        0       None   0
28   28                      pit_stops       INTEGER        0       None   0
29   29                    fastest_lap       BOOLEAN        0       None   0
30   30              driver_of_the_day       BOOLEAN        0       None   0
31   31                     grand_slam       BOOLEAN        0       None   0

In [19]:
query = f"SELECT * FROM race_result WHERE race_id = {race_info.iloc[0]['id']}"
print(query)
db.query(query)

SELECT * FROM race_result WHERE race_id = 1129

,race_id,position_display_order,position_number,position_text,driver_number,driver_id,constructor_id,engine_manufacturer_id,tyre_manufacturer_id,shared_car,...,pole_position,qualification_position_number,qualification_position_text,grid_position_number,grid_position_text,positions_gained,pit_stops,fastest_lap,driver_of_the_day,grand_slam
0,1129,1,1.0,1,81,oscar-piastri,mclaren,mercedes,pirelli,0,...,1,1,1,1,1,0.0,2,1,0,0
1,1129,2,2.0,2,63,george-russell,mercedes,mercedes,pirelli,0,...,0,2,2,3,3,1.0,2,0,0,0
2,1129,3,3.0,3,4,lando-norris,mclaren,mercedes,pirelli,0,...,0,6,6,6,6,3.0,2,0,0,0
3,1129,4,4.0,4,16,charles-leclerc,ferrari,ferrari,pirelli,0,...,0,3,3,2,2,-2.0,2,0,0,0
4,1129,5,5.0,5,44,lewis-hamilton,ferrari,ferrari,pirelli,0,...,0,9,9,9,9,4.0,2,0,1,0
5,1129,6,6.0,6,1,max-verstappen,red-bull,honda-rbpt,pirelli,0,...,0,7,7,7,7,1.0,2,0,0,0
6,1129,7,7.0,7,10,pierre-gasly,alpine,renault,pirelli,0,...,0,5,5,4,4,-3.0,2,0,0,0
7,1129,8,8.0,8,31,esteban-ocon,haas,ferrari,pirelli,0,...,0,14,14,14,14,6.0,2,0,0,0
8,1129,9,9.0,9,22,yuki-tsunoda,red-bull,honda-rbpt,pirelli,0,...,0,10,10,10,10,1.0,2,0,0,0
9,1129,10,10.0,10,87,oliver-bearman,haas,ferrari,pirelli,0,...,0,20,20,20,20,10.0,2,0,0,0
10,1129,11,11.0,11,12,kimi-antonelli,mercedes,mercedes,pirelli,0,...,0,4,4,5,5,-6.0,3,0,0,0
11,1129,12,12.0,12,23,alexander-albon,williams,mercedes,pirelli,0,...,0,15,15,15,15,3.0,2,0,0,0
12,1129,13,13.0,13,6,isack-hadjar,racing-bulls,honda-rbpt,pirelli,0,...,0,12,12,12,12,-1.0,2,0,0,0
13,1129,14,14.0,14,7,jack-doohan,alpine,renault,pirelli,0,...,0,11,11,11,11,-3.0,2,0,0,0
14,1129,15,15.0,15,14,fernando-alonso,aston-martin,mercedes,pirelli,0,...,0,13,13,13,13,-2.0,2,0,0,0
15,1129,16,16.0,16,30,liam-lawson,racing-bulls,honda-rbpt,pirelli,0,...,0,17,17,17,17,1.0,2,0,0,0
16,1129,17,17.0,17,18,lance-stroll,aston-martin,mercedes,pirelli,0,...,0,19,19,19,19,2.0,2,0,0,0
17,1129,18,18.0,18,5,gabriel-bortoleto,kick-sauber,ferrari,pirelli,0,...,0,18,18,18,18,0.0,2,0,0,0
18,1129,19,NaN,DNF,55,carlos-sainz-jr,williams,mercedes,pirelli,0,...,0,8,8,8,8,NaN,3,0,0,0
19,1129,20,NaN,DSQ,27,nico-hulkenberg,kick-sauber,ferrari,pirelli,0,...,0,16,16,16,16,NaN,2,0,0,0

In [25]:
# view available fields within qualifying result
query = "PRAGMA table_info(qualifying_result);"
db.query(query)

    cid                    name          type  notnull dflt_value  pk
0     0                 race_id       INTEGER        0       None   0
1     1  position_display_order       INTEGER        0       None   0
2     2         position_number       INTEGER        0       None   0
3     3           position_text    VARCHAR(4)        0       None   0
4     4           driver_number    VARCHAR(3)        0       None   0
5     5               driver_id  VARCHAR(100)        0       None   0
6     6          constructor_id  VARCHAR(100)        0       None   0
7     7  engine_manufacturer_id  VARCHAR(100)        0       None   0
8     8    tyre_manufacturer_id  VARCHAR(100)        0       None   0
9     9                    time   VARCHAR(20)        0       None   0
10   10             time_millis       INTEGER        0       None   0
11   11                      q1   VARCHAR(20)        0       None   0
12   12               q1_millis       INTEGER        0       None   0
13   13                      q2   VARCHAR(20)        0       None   0
14   14               q2_millis       INTEGER        0       None   0
15   15                      q3   VARCHAR(20)        0       None   0
16   16               q3_millis       INTEGER        0       None   0
17   17                     gap   VARCHAR(20)        0       None   0
18   18              gap_millis       INTEGER        0       None   0
19   19                interval   VARCHAR(20)        0       None   0
20   20         interval_millis       INTEGER        0       None   0
21   21                    laps       INTEGER        0       None   0

In [ ]:
query = f"SELECT * FROM qualifying_result WHERE race_id = {race_info.iloc[0]['id']}"
db.query(query)

SELECT * FROM qualifying_result WHERE race_id = 1129

,race_id,position_display_order,position_number,position_text,driver_number,driver_id,constructor_id,engine_manufacturer_id,tyre_manufacturer_id,time,...,q1_millis,q2,q2_millis,q3,q3_millis,gap,gap_millis,interval,interval_millis,laps
0,1129,1,1,1,81,oscar-piastri,mclaren,mercedes,pirelli,None,...,91392,1:30.454,90454.0,1:29.841,89841.0,None,NaN,None,NaN,15
1,1129,2,2,2,63,george-russell,mercedes,mercedes,pirelli,None,...,91494,1:30.664,90664.0,1:30.009,90009.0,+0.168,168.0,+0.168,168.0,20
2,1129,3,3,3,16,charles-leclerc,ferrari,ferrari,pirelli,None,...,91454,1:30.724,90724.0,1:30.175,90175.0,+0.334,334.0,+0.166,166.0,16
3,1129,4,4,4,12,kimi-antonelli,mercedes,mercedes,pirelli,None,...,91415,1:30.716,90716.0,1:30.213,90213.0,+0.372,372.0,+0.038,38.0,20
4,1129,5,5,5,10,pierre-gasly,alpine,renault,pirelli,None,...,91462,1:30.643,90643.0,1:30.216,90216.0,+0.375,375.0,+0.003,3.0,19
5,1129,6,6,6,4,lando-norris,mclaren,mercedes,pirelli,None,...,91107,1:30.560,90560.0,1:30.267,90267.0,+0.426,426.0,+0.051,51.0,18
6,1129,7,7,7,1,max-verstappen,red-bull,honda-rbpt,pirelli,None,...,91303,1:31.019,91019.0,1:30.423,90423.0,+0.582,582.0,+0.156,156.0,17
7,1129,8,8,8,55,carlos-sainz-jr,williams,mercedes,pirelli,None,...,91591,1:30.844,90844.0,1:30.680,90680.0,+0.839,839.0,+0.257,257.0,19
8,1129,9,9,9,44,lewis-hamilton,ferrari,ferrari,pirelli,None,...,91219,1:31.009,91009.0,1:30.772,90772.0,+0.931,931.0,+0.092,92.0,18
9,1129,10,10,10,22,yuki-tsunoda,red-bull,honda-rbpt,pirelli,None,...,91751,1:31.228,91228.0,1:31.303,91303.0,+1.462,1462.0,+0.531,531.0,17
10,1129,11,11,11,7,jack-doohan,alpine,renault,pirelli,None,...,91414,1:31.245,91245.0,None,NaN,None,NaN,None,NaN,13
11,1129,12,12,12,6,isack-hadjar,racing-bulls,honda-rbpt,pirelli,None,...,91591,1:31.271,91271.0,None,NaN,None,NaN,None,NaN,12
12,1129,13,13,13,14,fernando-alonso,aston-martin,mercedes,pirelli,None,...,91634,1:31.886,91886.0,None,NaN,None,NaN,None,NaN,15
13,1129,14,14,14,31,esteban-ocon,haas,ferrari,pirelli,None,...,91594,None,NaN,None,NaN,None,NaN,None,NaN,8
14,1129,15,15,15,23,alexander-albon,williams,mercedes,pirelli,None,...,92040,None,NaN,None,NaN,None,NaN,None,NaN,6
15,1129,16,16,16,27,nico-hulkenberg,kick-sauber,ferrari,pirelli,None,...,92067,None,NaN,None,NaN,None,NaN,None,NaN,17
16,1129,17,17,17,30,liam-lawson,racing-bulls,honda-rbpt,pirelli,None,...,92165,None,NaN,None,NaN,None,NaN,None,NaN,6
17,1129,18,18,18,5,gabriel-bortoleto,kick-sauber,ferrari,pirelli,None,...,92186,None,NaN,None,NaN,None,NaN,None,NaN,6
18,1129,19,19,19,18,lance-stroll,aston-martin,mercedes,pirelli,None,...,92283,None,NaN,None,NaN,None,NaN,None,NaN,9
19,1129,20,20,20,87,oliver-bearman,haas,ferrari,pirelli,None,...,92373,None,NaN,None,NaN,None,NaN,None,NaN,6

In [26]:
# view available fields within free practice N result
query = "PRAGMA table_info(free_practice_3_result);"
db.query(query)

    cid                    name          type  notnull dflt_value  pk
0     0                 race_id       INTEGER        0       None   0
1     1  position_display_order       INTEGER        0       None   0
2     2         position_number       INTEGER        0       None   0
3     3           position_text    VARCHAR(4)        0       None   0
4     4           driver_number    VARCHAR(3)        0       None   0
5     5               driver_id  VARCHAR(100)        0       None   0
6     6          constructor_id  VARCHAR(100)        0       None   0
7     7  engine_manufacturer_id  VARCHAR(100)        0       None   0
8     8    tyre_manufacturer_id  VARCHAR(100)        0       None   0
9     9                    time   VARCHAR(20)        0       None   0
10   10             time_millis       INTEGER        0       None   0
11   11                     gap   VARCHAR(20)        0       None   0
12   12              gap_millis       INTEGER        0       None   0
13   13                interval   VARCHAR(20)        0       None   0
14   14         interval_millis       INTEGER        0       None   0
15   15                    laps       INTEGER        0       None   0

In [27]:
query = f"SELECT * FROM free_practice_3_result WHERE race_id = {race_info.iloc[0]['id']}"
db.query(query)

,race_id,position_display_order,position_number,position_text,driver_number,driver_id,constructor_id,engine_manufacturer_id,tyre_manufacturer_id,time,time_millis,gap,gap_millis,interval,interval_millis,laps
0,1129,1,1,1,81,oscar-piastri,mclaren,mercedes,pirelli,1:31.646,91646,None,NaN,None,NaN,13
1,1129,2,2,2,4,lando-norris,mclaren,mercedes,pirelli,1:32.314,92314,+0.668,668.0,+0.668,668.0,18
2,1129,3,3,3,16,charles-leclerc,ferrari,ferrari,pirelli,1:32.480,92480,+0.834,834.0,+0.166,166.0,19
3,1129,4,4,4,63,george-russell,mercedes,mercedes,pirelli,1:32.827,92827,+1.181,1181.0,+0.347,347.0,13
4,1129,5,5,5,12,kimi-antonelli,mercedes,mercedes,pirelli,1:32.916,92916,+1.270,1270.0,+0.089,89.0,12
5,1129,6,6,6,10,pierre-gasly,alpine,renault,pirelli,1:32.974,92974,+1.328,1328.0,+0.058,58.0,18
6,1129,7,7,7,6,isack-hadjar,racing-bulls,honda-rbpt,pirelli,1:33.023,93023,+1.377,1377.0,+0.049,49.0,15
7,1129,8,8,8,1,max-verstappen,red-bull,honda-rbpt,pirelli,1:33.027,93027,+1.381,1381.0,+0.004,4.0,13
8,1129,9,9,9,55,carlos-sainz-jr,williams,mercedes,pirelli,1:33.092,93092,+1.446,1446.0,+0.065,65.0,15
9,1129,10,10,10,44,lewis-hamilton,ferrari,ferrari,pirelli,1:33.111,93111,+1.465,1465.0,+0.019,19.0,18
10,1129,11,11,11,31,esteban-ocon,haas,ferrari,pirelli,1:33.240,93240,+1.594,1594.0,+0.129,129.0,17
11,1129,12,12,12,7,jack-doohan,alpine,renault,pirelli,1:33.347,93347,+1.701,1701.0,+0.107,107.0,18
12,1129,13,13,13,30,liam-lawson,racing-bulls,honda-rbpt,pirelli,1:33.370,93370,+1.724,1724.0,+0.023,23.0,14
13,1129,14,14,14,14,fernando-alonso,aston-martin,mercedes,pirelli,1:33.548,93548,+1.902,1902.0,+0.178,178.0,18
14,1129,15,15,15,23,alexander-albon,williams,mercedes,pirelli,1:33.753,93753,+2.107,2107.0,+0.205,205.0,16
15,1129,16,16,16,87,oliver-bearman,haas,ferrari,pirelli,1:34.335,94335,+2.689,2689.0,+0.582,582.0,18
16,1129,17,17,17,18,lance-stroll,aston-martin,mercedes,pirelli,1:34.363,94363,+2.717,2717.0,+0.028,28.0,16
17,1129,18,18,18,5,gabriel-bortoleto,kick-sauber,ferrari,pirelli,1:34.518,94518,+2.872,2872.0,+0.155,155.0,16
18,1129,19,19,19,27,nico-hulkenberg,kick-sauber,ferrari,pirelli,1:34.636,94636,+2.990,2990.0,+0.118,118.0,7
19,1129,20,20,20,22,yuki-tsunoda,red-bull,honda-rbpt,pirelli,1:34.965,94965,+3.319,3319.0,+0.329,329.0,15

In [29]:
# Try to find rounds in 2025
query = "SELECT id, official_name FROM race WHERE year = 2025"
race_info = db.query(query)
print(race_info)

      id                                      official_name
0   1126  Formula 1 Louis Vuitton Australian Grand Prix ...
1   1127         Formula 1 Heineken Chinese Grand Prix 2025
2   1128          Formula 1 Lenovo Japanese Grand Prix 2025
3   1129         Formula 1 Gulf Air Bahrain Grand Prix 2025
4   1130        Formula 1 stc Saudi Arabian Grand Prix 2025
5   1131         Formula 1 Crypto.com Miami Grand Prix 2025
6   1132  Formula 1 AWS Gran Premio del Made in Italy e ...
7   1133      Formula 1 TAG Heuer Grand Prix de Monaco 2025
8   1134        Formula 1 Aramco Gran Premio de España 2025
9   1135        Formula 1 Pirelli Grand Prix du Canada 2025
10  1136     Formula 1 MSC Cruises Austrian Grand Prix 2025
11  1137    Formula 1 Qatar Airways British Grand Prix 2025
12  1138   Formula 1 Moët & Chandon Belgian Grand Prix 2025
13  1139         Formula 1 Lenovo Hungarian Grand Prix 2025
14  1140           Formula 1 Heineken Dutch Grand Prix 2025
15  1141        Formula 1 Pirelli Gran Premio d'Italia 2025
16  1142  Formula 1 Qatar Airways Azerbaijan Grand Prix ...
17  1143  Formula 1 Singapore Airlines Singapore Grand P...
18  1144  Formula 1 MSC Cruises United States Grand Prix...
19  1145  Formula 1 Gran Premio de la Ciudad de México 2025
20  1146  Formula 1 MSC Cruises Grande Prêmio de São Pau...
21  1147       Formula 1 Heineken Las Vegas Grand Prix 2025
22  1148      Formula 1 Qatar Airways Qatar Grand Prix 2025
23  1149  Formula 1 Etihad Airways Abu Dhabi Grand Prix ...