# Exploratory Data Analysis

Pull data from f1db and create feature vectors.

from

In [2]:
import sys
from pathlib import Path

# Get the project root (up one level from 'notebooks')
project_root = Path.cwd().parent

# Add the project root to sys.path if it's not already there
if str(project_root) not in sys.path:
    sys.path.append(str(project_root))

# Now you can import from the src directory
from src.database import F1DataManager

# Initialize the manager
db = F1DataManager()
df = db.get_driver_stats()
df.head()

,full_name,total_race_wins,total_podiums,total_points
0,Adderly Fong Cheun-yue,0,0,0.0
1,Adolf Brudes von Breslau,0,0,0.0
2,Adolfo Julio Carlos Schwelm Cruz,0,0,0.0
3,Adrián Campos Suñer,0,0,0.0
4,Adrian Sutil,0,0,124.0

In [3]:
# View sorted table entries
query = "SELECT name FROM sqlite_master WHERE type='table' ORDER BY name;" 
db.query(query)

                                name
0                            chassis
1                            circuit
2                        constructor
3             constructor_chronology
4                          continent
5                            country
6                             driver
7         driver_family_relationship
8                             engine
9                engine_manufacturer
10                           entrant
11                        grand_prix
12                              race
13         race_constructor_standing
14                         race_data
15              race_driver_standing
16                            season
17                season_constructor
18       season_constructor_standing
19                     season_driver
20            season_driver_standing
21        season_engine_manufacturer
22                    season_entrant
23            season_entrant_chassis
24        season_entrant_constructor
25             season_entrant_driver
26             season_entrant_engine
27  season_entrant_tyre_manufacturer
28          season_tyre_manufacturer
29                 tyre_manufacturer

In [4]:
query = "PRAGMA table_info(race_result);"
db.query(query)

    cid                           name          type  notnull dflt_value  pk
0     0                        race_id       INTEGER        0       None   0
1     1         position_display_order       INTEGER        0       None   0
2     2                position_number       INTEGER        0       None   0
3     3                  position_text    VARCHAR(4)        0       None   0
4     4                  driver_number    VARCHAR(3)        0       None   0
5     5                      driver_id  VARCHAR(100)        0       None   0
6     6                 constructor_id  VARCHAR(100)        0       None   0
7     7         engine_manufacturer_id  VARCHAR(100)        0       None   0
8     8           tyre_manufacturer_id  VARCHAR(100)        0       None   0
9     9                     shared_car       BOOLEAN        0       None   0
10   10                           laps       INTEGER        0       None   0
11   11                           time   VARCHAR(20)        0       None   0
12   12                    time_millis       INTEGER        0       None   0
13   13                   time_penalty   VARCHAR(20)        0       None   0
14   14            time_penalty_millis       INTEGER        0       None   0
15   15                            gap   VARCHAR(20)        0       None   0
16   16                     gap_millis       INTEGER        0       None   0
17   17                       gap_laps       INTEGER        0       None   0
18   18                       interval   VARCHAR(20)        0       None   0
19   19                interval_millis       INTEGER        0       None   0
20   20                 reason_retired  VARCHAR(100)        0       None   0
21   21                         points  DECIMAL(8,2)        0       None   0
22   22                  pole_position       BOOLEAN        0       None   0
23   23  qualification_position_number       INTEGER        0       None   0
24   24    qualification_position_text    VARCHAR(4)        0       None   0
25   25           grid_position_number       INTEGER        0       None   0
26   26             grid_position_text    VARCHAR(2)        0       None   0
27   27               positions_gained       INTEGER        0       None   0
28   28                      pit_stops       INTEGER        0       None   0
29   29                    fastest_lap       BOOLEAN        0       None   0
30   30              driver_of_the_day       BOOLEAN        0       None   0
31   31                     grand_slam       BOOLEAN        0       None   0

In [ ]:
query = "SELECT name, total_championship_wins, total_race_wins FROM constructor"
db.query(query)

   cid  name     type  notnull dflt_value  pk
0    0  year  INTEGER        1       None   1